# Generated by Django 3.1.5 on 2021-01-19 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_payment_usercourse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
